### PR TITLE
Major update

### PR DESCRIPTION
**Pull request by PiOverFour**
Hello,
so I started using your mode, and noticed the highlighting wasn’t up to date with the latest versions of Ink. I updated it a bit, then kind of got carried away and implemented a lot of other stuff. This pull request contains:
- updated syntax highlighting;
- automatic indentation;
- the ability to follow links to stitches, knots and labels in the current document, as well as includes (but not stitches, knots and labels in other documents);
- an outline system copied from markdown-mode (inherited from org-mode), whereby you can fold knots and stitches;
- updated `ink-play` to allow to start the game from the knot or stitch at point;
- optionally, errors are checked and displayed using flycheck;
- snippets for YASnippets;
- a menu for command discoverability.

Now I don’t know if you’ll want to maintain this much-expanded program since the code hadn’t been developed in years—in which case I will. I’m making the pull request anyway, in particular because the package is already published on MELPA and I thought it would be convenient for potential users to keep the same package name.

Also, I reused a lot of GPL code from markdown-mode and other places, so I need to change the license since it has a strong copyleft. In order to do that, I need your permission for the lines that you wrote. They’re MIT, so although I can sublicense the source, without your agreement to relicense your code under the GPL I would need to keep the MIT license text in addition to the GPL, which seems redundant.

Thanks for enabling me to improve upon your package :)

### CODE REVIEW

**Comment by Kungsgeten** [comment]
Hi! I'm happy to see that you've found use of `ink-mode`. I mostly wrote it as an exercise in writing a major-mode, and then didn't use it much. There's no problem on my part if you feel the need to change the license. Since I do not plan to continue development myself I think it'll be best if you step in as the maintainer, if its okay with you. I can give you permissions to manage the Github repository.

**Comment by PiOverFour** [comment]
That’s even better, thank you!

**Comment by Kungsgeten** [comment]
You're welcome. I've invited you to be a collaborator. I haven't used that feature before, so I hope it does what I intend :) Please let me know if it works (I think you should be able to push directly into the repo).

**Comment by PiOverFour** [comment]
Thank you, I can confirm I have push access to the repo, and just pushed a test branch while rewriting my work’s history.

The update I’m making is also a way for me to learn elisp development, and it’s a cool project!
Also thanks for the licensing, I know some developers prefer to stick to permissive licenses.

I will close this now and push directly to the repo when I’m ready. :)

**Pull request closed without merging**
